title: "Deterministic Blog"
author: "Mehmet Kutay Bozkurt"
description: "Made with <b style=\"color: #bf616a;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"
google_analytics: G-Z62CEK3M0E

# Layout

# Menu

navigation: # file, url, title
  - {file: "about.md", url: "/about/", title: "About"}
  - {file: "archive.html", url: "/archive/", title: "Archive"}

external: # for available icons see fontawesome.com/icons
  # - {title: "Mail", icon: "envelope", url: "mailto:mkutaybzkrt01101011@gmail.com", include_title: false}
  - {title: "Github", icon: "github", url: "https://github.com/MKutay", include_title: false}
  - {title: "Email Me", icon: "envelope", url: "mailto:hello@mkutay.dev", include_title: true}
  - {title: "Sponsor Me", icon: "heart", url: "https://github.com/sponsors/MKutay?o=esb", include_title: true}
  - {title: "Feed", icon: "rss", url: "https://blog.mkutay.dev/feed.xml", include_title: true}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jekyll-sitemap

include: ["_pages"]
